# Auto-label PRs based on changed files and PR title
# Configuration for actions/labeler v5
# Reference: https://github.com/actions/labeler

# Platform labels
platform:ios:
- changed-files:
  - any-glob-to-any-file:
    - 'ios/**/*'
    - '*.swift'
    - '*.mm'
    - '*.h'
    - '*.podspec'

platform:android:
- changed-files:
  - any-glob-to-any-file:
    - 'android/**/*'
    - '*.kt'
    - '*.gradle'
    - '*.xml'

# Area labels
area:typescript:
- changed-files:
  - any-glob-to-any-file:
    - 'src/**/*.ts'
    - 'src/**/*.tsx'
    - '*.ts'
    - '*.tsx'
    - 'tsconfig*.json'

area:ios-native:
- changed-files:
  - any-glob-to-any-file:
    - 'ios/**/*.swift'
    - 'ios/**/*.mm'
    - 'ios/**/*.h'

area:android-native:
- changed-files:
  - any-glob-to-any-file:
    - 'android/**/*.kt'
    - 'android/**/*.java'

area:docs:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.md'
    - 'docs/**/*'
    - 'docs-internal/**/*'

area:ci:
- changed-files:
  - any-glob-to-any-file:
    - '.github/**/*'
    - '**/.github/**/*'

area:example:
- changed-files:
  - any-glob-to-any-file:
    - 'example/**/*'

area:config:
- changed-files:
  - any-glob-to-any-file:
    - '*.json'
    - '*.js'
    - '*.mjs'
    - 'babel.config.js'
    - 'jest.config.js'
    - 'eslint.config.mjs'
    - 'turbo.json'

# Type labels (based on PR title and branch)
type:bug:
- any:
  - head-branch: ['^bug/', '^fix/', '^hotfix/']
  - title: ['.*\[Bug\].*', '.*\[Fix\].*', '.*fix.*', '.*bug.*']

type:feature:
- any:
  - head-branch: ['^feature/', '^feat/']
  - title: ['.*\[Feature\].*', '.*\[Feat\].*', '.*feat.*', '.*feature.*']

type:docs:
- any:
  - head-branch: ['^docs/', '^documentation/']
  - title: ['.*\[Docs\].*', '.*\[Documentation\].*', '.*docs.*', '.*documentation.*']

type:refactor:
- any:
  - head-branch: ['^refactor/']
  - title: ['.*\[Refactor\].*', '.*refactor.*']

type:chore:
- any:
  - head-branch: ['^chore/', '^ci/']
  - title: ['.*\[Chore\].*', '.*\[CI\].*', '.*chore.*', '.*ci.*']

# Priority labels
priority:high:
- title: ['.*\[High Priority\].*', '.*\[P0\].*', '.*\[Critical\].*']

priority:low:
- title: ['.*\[Low Priority\].*', '.*\[P3\].*']
