name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.26.0
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v5.0.0
      with:
        node-version-file: .nvmrc
        cache: 'pnpm'

    - name: Restore dependencies
      id: pnpm-cache
      uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: |
          **/node_modules
          ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Cache dependencies
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: |
          **/node_modules
          ~/.pnpm-store
        key: ${{ steps.pnpm-cache.outputs.cache-primary-key }}
